### ISSUE TITLE
Identifier syntax

### ISSUE THREAD

**Issue by LouisAmon** [nuage-studio/pulumi-snowflake#23]
https://docs.snowflake.net/manuals/sql-reference/identifiers-syntax.html

According to the Snowflake doc, you can't write `hello-world` isn't a valid identifier unless double quoted `"hello-world"` in the SQL query.

My suggestion is that we should validate wether the identifier is allowed unquoted (ex: `hello_world`) firstly, and if it isn't then simply add double quotes around it.

In the case of `hello_world`, the user will then be able to query it using any case (ex: `SELECT * FROM HELLO_WORLD`).
In the case of `hello-world`, the user will have to use case-sensistive syntax to query it (ex: `SELECT * FROM "hello-world"`)

It is up to him to know about this naming rules, but we could put a warning and/or link to the Snowflake doc in the docstring.

**Comment by LouisAmon** [comment]
What do you think @cloudspeak ?

**Comment by cloudspeak** [comment]
This is fine in situations where we know that we expect an identifier, but if we're not careful this will lead us back to the more strongly-defined typed attributes I had started originally.  For example, suppose we pass this to the resource:

```python
MyResource(type="CSV")
```

How do we know if this is meant to be a string or an identifier?  We would have to start hard-coding this information into the provider again, which might be a step backwards.  If it's meant to be a string then removing the quotes would be (as far as I know) a syntax error.

My question would be: does it matter if we enquote _all_ identifiers regardless of whether they need quotes?  It seems that Snowflake is ok with this, and it would save complicated logic.  That's what the recent updated to the codebase do.

**Comment by LouisAmon** [comment]
If we enquote all identifiers then we lose the case-insensitivity

From my own experience, it's a big feature regression : most people beginning with Snowflake & reading the docs will have gotten used to the case-insensitivity when playing around with the Snowflake console.

Typically, we don't want a developer putting `name='foo'` to be unable to query `SELECT * FROM FOO` : he won't immediately understand that we enquoted `"foo"` thus making it case-sensitive

Maybe a safe start would be to only apply this sensible quoting logic to the `name` parameter for now (and not `type` in your example)

**Comment by cloudspeak** [comment]
Ah yes, that's a good point.  Ok, applying to `name` only definitely sounds sensible.  I would be concerned that applying it further will get us back where we were, and explicitly defining the types of all identifier fields so we can distinguish them from strings!

**Comment by LouisAmon** [comment]
Could you please [close](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) in your commit by using the right keyword reference ?

(otherwise i'll just link it in the PR)
