### ISSUE TITLE
Implement `Table` resource

### ISSUE THREAD

**Issue by LouisAmon** [nuage-studio/pulumi-snowflake#26]
https://docs.snowflake.net/manuals/sql-reference/sql/create-table.html

```python
table = Table(
    resource_name='acme-dev-tracking',
    name='tracking',
    database=db,
    schema=schema,
    comment='Tracking data from the website',
    cluster_by=['to_date(timestamp)', 'id'],
    data_retention_time_in_days=7,
)
```

**Comment by cloudspeak** [comment]
Just a suggestion as this is tagged as help wanted - maybe this would be a good case for creating another class to represent columns?  E.g.:

```python
table = Table(
    resource_name='acme-dev-tracking',
    name='tracking',
    database=db,
    schema=schema,
    comment='Tracking data from the website',
    columns=[
      Column(name='firstCol', type='INT', not_null=True),
      Column(name='secondCol', type='INT'),
    ]
    WIP
)
```

It would probably be nicer for the user than having to pass columns as dicts, which would required them looking up the right field names in the documentation.

**Comment by LouisAmon** [comment]
Seems like a good idea indeed... but then we'd end up adventuring into ORM

Django does a fine job at that, Alembic has native support for Snowflake and there's also DBT... feels like we're reinventing the wheel

It could be a nice first step doing it the way you suggest it, but it should be done in a limited way

**Comment by LouisAmon** [comment]
I added above:
```python
cluster_by=['to_date(timestamp)', 'id'],
data_retention_time_in_days=7,
```

I think your approach is right for the columns
