### ISSUE TITLE
Implementing `FileFormat` resource

### ISSUE THREAD

**Issue by LouisAmon** [nuage-studio/pulumi-snowflake#9]
https://docs.snowflake.net/manuals/sql-reference/sql/create-file-format.html

```python
fr_csv_format = FileFormat(
    resource_name='fr-csv-format',
    name='fr-csv',
    database='acme',
    schema='dev',
    comment='CSV files in France have a ; separator',
    type='csv',
    format_type_options={
        'field_delimiter': ';'
    }
)
```

**Comment by cloudspeak** [comment]
Although the docs describe a `formatTypeOptions` structure, it appears this structure is placed inline into the create statement like so:

```sql
create or replace file format my_csv_format
  type = csv
  field_delimiter = '|'
  skip_header = 1
  ...
```

Would we rather follow suit and keep our format options at the top level like this:

```python
fr_csv_format = FileFormat(
   ...
    type='csv',
    field_delimiter=';'
    skip_header=1
)
```

or keep with the structure you specified, where `formatTypeOptions` are a separate dict?
